### ISSUE TITLE
Add a dev setup guide

### ISSUE THREAD

**Issue by pterygaphykion** [runrig-coop/rgo-early-warning-system#1]
Document how to set up a dev environment so new contributors can easily get set up.

A/C:
- setting up rust
- setting up tauri
- how to build project

**Comment by jgaehring** [comment]
I had a few notes stashed from yesterday that I tidied up into a commit over on my fork: https://github.com/jgaehring/rgo-early-warning-system/commit/10b8418aa6ad8156570a1074a6af834f591598cc

Dunno if we want to build on top of that and keep it in the `README` itself or start a separate `CONTRIBUTING.md` or something like that, but figured it could be a simple start that covers the basics. I'm going to branch off that and keep working there for #9, but I can always drop the commit if we don't want to use it.

**Comment by jgaehring** [comment]
I think we can close this now and defer to #4 for the addition of any more detailed setup instructions.
